### ISSUE TITLE
Unprocessable Entity Error in Order API

### ISSUE THREAD

**Issue by Kasi-mir** [microapps/Shopify-api-node#100]
Sorry this may sound basic, but for the earth of me I can't figure out why I'm getting an unprocessable entity error on this node module when trying to process an order. I'm used to Shopify returning a piece of info telling why its failing, but on the earth of me I can't figure how to get that to work with this module.

I tried a minimal example, which works fine as a direct call, but does not work with module, any idea why? (The variant and product does exist)

`shopify.order.create({
    "order": {
        "send_receipt": true,
        "send_fulfillment_receipt": true,
        "financial_status": "pending",
        "email": "asd@gmail.com",
        "currency": "GBP",
        "line_items": [{
            "product_id": "4384307335",
            "variant_id": "15017097223",
            "price": "255",
            "quantity": "3"
        }]
    }
}).then(orders => console.log(orders)).catch(err => console.error(err));`

**Comment by lpinca** [comment]
Hi,
use the order data directly. The module automatically wraps the data in the `order` property.
Try like this:

```js
shopify.order.create({
  send_receipt: true,
  send_fulfillment_receipt: true,
  financial_status: 'pending',
  email: 'asd@gmail.com',
  currency: 'GBP',
  line_items: [
    {
      product_id: '4384307335',
      variant_id: '15017097223',
      price: '255',
      quantity: '3'
    }
  ]
}).then(order => console.log(order));
```

When you get an error, the response is attached to the error so you can get more details by reading its body:

```js
console.log(err.response.body);
```

**Comment by Kasi-mir** [comment]
Hi Ipinca,
I feel rather stupid now. Excellent thanks for the input, sorted the issue.

**Comment by lpinca** [comment]
No, you are right, it's confusing. We should document this behavior (PR's are welcome).
I close this. Please post back if needed.
