### ISSUE TITLE
Shopify Events ?

### ISSUE THREAD

**Issue by daslicht** [microapps/Shopify-api-node#101]
Hi,
is it possible to listen for Shopify Events ?
see: https://help.shopify.com/api/reference/event

Cheers Marc

**Comment by lpinca** [comment]
You can list or count events but I don't think you can listen to them using the API.
See "What can you do with Event?" in the docs.

**Comment by daslicht** [comment]
Thank you for you fast Reply!!!
Ok I "What can you do with Event?" says that I can get events.
So I would have to poll and see if there are new events ? huh?

**Comment by lpinca** [comment]
Yeah, it's a bit unfortunate as it's not a stream API so you can't really listen to them unless you poll for new events as you said. Given the API call limits this is probably a no go.  
[Webhooks](https://help.shopify.com/api/reference/webhook) may be a better way to "listen" to events.

**Comment by daslicht** [comment]
ahh ok its more like an event feed, thanks i will have a look at webhooks !
