### ISSUE TITLE
Delete metafield that belongs to a product

### ISSUE THREAD

**Issue by Kasi-mir** [microapps/Shopify-api-node#102]
Hello,

Quick question, as I could not figure this out with the documentation. How would one delete a metafield belonging to a product?

Thanks in advance

**Comment by lpinca** [comment]
This should work:

```js
shopify.metafield.delete(721389482);
```

From the documentation:

> Delete an existing store metafield by id. A metafield belonging to any resource can be deleted this way.

**Comment by Kasi-mir** [comment]
Why does Shopify provide an API endpoint specifically for metafields connected to products? Are metafields IDs always unique regardless what its parent resource is?

**Comment by lpinca** [comment]
> Why does Shopify provide an API endpoint specifically for metafields connected to products?

It's only for products, if you look at the diagram at the beginning of the page (https://help.shopify.com/api/reference/metafield) you'll see that metafields can be added to many resources.

So `DELETE /admin/rrders/#{id}/metafields/#{id}.json` should also be valid.

> Are metafields IDs always unique regardless what its parent resource is?

This is a good question, and I honestly don't know. I think so, but the best way to find it out is to create 2 metafields for 2 different resources and check their ids.

**Comment by Kasi-mir** [comment]
Thanks for the input Ipinca, I'll do some testing and get back to you. If the metafields are unique then I have no problem using `shopify.metafield.delete(721389482);` but obviously if they are not then its a bit tricky with the current way this module is laid out.

**Comment by lpinca** [comment]
Yes, that's correct, if the metafields ids are not unique, then `shopify-api-node` does not provide a clean way to delete a metafield of a resource unless the private `request` method is used directly.

**Comment by Kasi-mir** [comment]
Done some testing. 

Seems like the IDs are unique and probably just increment the same database. Awesome, thanks again for your input.

**Comment by lpinca** [comment]
No problem.

**Comment by lpinca** [comment]
Closing, feel free to reopen if needed.
