### ISSUE TITLE
Rename the project to Shopify node

### ISSUE THREAD

**Issue by alexandresaiz** [microapps/shopify-api-node#84]
Either from a "SEO" inside opensource community and for other reasons "obvious" to someone, I think it'd be wise to rename the project to be sth like Shopify node or alike. 

@Alua-Kinzhebayeva @lpinca @carlosvillu @davidgf thoughts?

**Comment by lpinca** [comment]
It's hard to find a good available name on npm:

- https://www.npmjs.com/search?q=shopify-node
- https://www.npmjs.com/search?q=node-shopify

unless we use a [scoped name](https://docs.npmjs.com/misc/scope).

**Comment by lpinca** [comment]
If we go for a scoped name I would just use "shopify".

**Comment by alexandresaiz** [comment]
We definitely want to get rid of "nodify" "node" and keep it cleaner with just: Shopify.
Either scopes or I can try to approach: https://www.npmjs.com/package/shopify to see if they'd be ok to release their name

**Comment by lpinca** [comment]
:+1:

**Comment by lpinca** [comment]
Here are some available names that might be good:

- shoppify
- shopify-api-node
- shopify.node
- shopify-nodejs

**Comment by alexandresaiz** [comment]
done!
https://github.com/microapps/shopify-api-node
