### ISSUE TITLE
Undocumented API support

### ISSUE THREAD

**Issue by SEAPUNK** [microapps/Shopify-api-node#91]
For some reason, Shopify has a fair amount of undocumented APIs, most notably the search endpoints.

For example, the [Variants API](https://help.shopify.com/api/reference/product_variant) only has a few select endpoints documented, but there's a seemingly undocumented endpoint: `GET /admin/variants/search.json`.

![](http://i.imgur.com/iH2aHZz.png)

Looking further into this, it seems that they're [still working on documenting and then releasing it "soon"](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/api-product-variant-search-183152#comment-184293), but I still feel it would be good to leverage this functionality now.

Will you be willing to include undocumented/beta API functions to this library?

**Comment by alexandresaiz** [comment]
@SEAPUNK we're only adding supported API's
