### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by SEAPUNK** [microapps/Shopify-api-node#96]
IIRC, `got` doesn't have a default timeout, which seems to mean that a request can take forever if the program missed or just has not received a response. One of my programs that I wrote that utilizes this module seems to be getting bit by this problem.

I do not see a place where I can configure a timeout in this module; will support for this be added?

**Comment by lpinca** [comment]
Yes it makes sense. Ideally we should make this an option, fall back to a default value if the option is not provided and forward that value to got. I'm not totally sure what interface to use though.
We can add an additional options argument to the constructor or change the construct to only accept an options object (this is a breaking change).
Another option is to add a `configure` method to allow configuration once the instance has been created but meh I'm not really happy with this.

**Comment by SEAPUNK** [comment]
Ultimately, I personally prefer the breaking change to be implemented, which would then deconstruct the object into instance properties, where `requestOptions` would be one of them, which would be an object that gets additionally applied into the generated request option object, as kind of an override.

```js
class API {
  constructor (options) {
    this.requestOptions = options
  }

  request () {
    let options = assign(
        // ...
    )
    if (this.requestOptions) {
      options = assign(options, this.requestOptions)
    }
    // [...]
  }
}
```

...but because you probably don't want to immediately make the breaking change, a non-breaking change that would be a step towards such a change would be just doing the instance property of `this.requestOptions`, document it, and have people set it immediately after construction. It's not pretty, but it's also possibly not going to be used often, and to me is the cleanest way to do this if we're looking at the big picture.

```js
const api = new API()
api.requestOptions = {timeout: 30000}
```

Also, would setting a default request timeout be considered a breaking change, feature addition, or a bug fix?

**Comment by lpinca** [comment]
It's a fix and yes the breaking change is probably the cleanest. :-1: on using properties directly added by the user like `shopify.requestOptions` it doens't matter if it's a setter.
The module has only ~500 downloads per month and only 1 dependent so I'm not really worried about bumping the major version.
We can also avoid adding a namespace for the request options, a `timeout` option is perfectly fine.

**Comment by SEAPUNK** [comment]
> We can also avoid adding a namespace for the request options, a timeout option is perfectly fine.

+0, I'm a bit leery having _just_ the `timeout` option, considering the only place it's affected is `got`, but at the same time, I don't really have a use case for being able to control all of the options sent to the request function.

If we're adding a default timeout, what should it be? I vote for 1 minute.

**Comment by lpinca** [comment]
Yes that should be ok, and it's a default which can be changed later if it doesn't fit.

**Comment by SEAPUNK** [comment]
Alright, cool.

Are you going to make the change, or shall I open up a PR for it?

**Comment by lpinca** [comment]
If you want to send a pr I'll happily review it.

**Comment by SEAPUNK** [comment]
Alright, but I'll only have time to start working on it either tomorrow or the day after.

**Comment by lpinca** [comment]
Sure no problem, the change shouldn't be that big, maybe there will be some tests to fix.

**Comment by SEAPUNK** [comment]
#97 is the options object construction, and then I'll add another PR that adds the timeout option.

**Comment by SEAPUNK** [comment]
#98 is the timeout feature.
